services:
  db:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devdb
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"